#启动默认音量
volume=30

#自动加载外部字幕文件方式
#no:	Don't automatically load external subtitle files.
#exact:	Load the media filename with subtitle file extension and possibly language suffixes (default).
#fuzzy:	Load all subs containing the media filename.
#all:	Load all subs in the current and --sub-file-paths directories.
sub-auto=all
